Repository coders-camp-2021-best-team/Freeverse, pull requests merged in 2022-01, with the labels that each got.

#12 fix: Fix project setup
  .env.example
  .gitignore
  .prettierrc
  README.md
  package-lock.json
  package.json
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/App.css
  src/App.js
  src/App.jsx
  src/App.test.js
  src/components/atoms/Button/Button.jsx
  src/components/atoms/Button/Button.scss
  src/components/atoms/Text/Text.jsx
  src/components/atoms/Text/Text.scss
  src/components/atoms/index.jsx
  src/components/index.jsx
  src/components/molecules/index.jsx
  src/components/organisms/Counter/Counter.jsx
  src/components/organisms/Counter/Counter.test.jsx
  src/components/organisms/HelloWorld/HelloWorld.jsx
  src/components/organisms/HelloWorld/HelloWorld.test.jsx
  src/components/organisms/index.jsx
  src/hooks/index.jsx
  src/hooks/useDummy.jsx
  src/index.css
  src/index.js
  src/logo.svg
  src/pages/Home/Home.jsx
  src/pages/index.jsx
  src/reportWebVitals.js
  src/styles/global.scss
  src/styles/variables.scss
  src/utils/index.jsx
  yarn.lock
Labels: type: fix, scope: app, priority: high

#32 feat: Add routing solution
  package.json
  public/netlify.toml
  src/App.jsx
  src/components/atoms/ProtectedRoute/ProtectedRoute.jsx
  src/components/atoms/index.jsx
  src/components/organisms/Header/Header.jsx
  src/pages/BaseScreen/BaseScreen.jsx
  src/pages/Chat/Chat.jsx
  src/pages/EditProfile/EditProfile.jsx
  src/pages/Error/Error.jsx
  src/pages/FeedScreen/FeedScreen.jsx
  src/pages/Home/Home.jsx
  src/pages/Profile/Profile.jsx
  src/pages/index.jsx
  yarn.lock
Labels: type: feat, priority: medium

#27 ci: Add `ci.yml` workflow configuration
  .eslintrc
  .github/workflows/ci.yml
  .husky/pre-commit
  .npmrc
  .prettierrc
  README.md
  package.json
  src/App.jsx
  src/components/atoms/Button/Button.jsx
  src/components/atoms/ProtectedRoute/ProtectedRoute.jsx
  src/components/atoms/Text/Text.jsx
  src/components/atoms/Text/Text.scss
  src/components/organisms/Counter/Counter.jsx
  src/components/organisms/Header/Header.jsx
  src/components/organisms/index.jsx
  src/index.jsx
  src/pages/BaseScreen/BaseScreen.jsx
  src/pages/Chat/Chat.jsx
  src/pages/EditProfile/EditProfile.jsx
  src/pages/Error/Error.jsx
  src/pages/FeedScreen/FeedScreen.jsx
  src/pages/Home/Home.jsx
  src/pages/Profile/Profile.jsx
  src/pages/index.jsx
  src/styles/mixins.scss
  src/styles/variables.scss
  yarn.lock
Labels: type: chore, scope: app, priority: high

#36 chore: Add VSCode workspace with recommended extensions
  .gitignore
  Freeverse.code-workspace
Labels: type: chore, scope: app, priority: low

#39 fix: Add cache to `ci.yml` workflow configuration
  .github/workflows/ci.yml
Labels: scope: bug, type: chore, priority: high

#44 Add: Error Page
  src/App.jsx
  src/components/atoms/Button/Button.scss
  src/components/atoms/Text/Text.jsx
  src/components/organisms/Header/Header.jsx
  src/index.jsx
  src/pages/Error/Error.jsx
  src/pages/Error/Error.scss
  src/pages/Home/Home.jsx
  src/routes/Routes.js
  src/styles/global.scss
  src/styles/variables.scss
Labels: scope: ui, type: feat, priority: medium

#51 feat: add useResponsive custom hook
  src/pages/Error/Error.scss
  src/styles/global.scss
  src/styles/mixins.scss
  src/utils/useResponsive.js
Labels: scope: app, type: feat, priority: medium
