Repository coders-camp-2021-best-team/Freeverse, pull requests merged in 2022-02, with the labels that each got.

#63 feat: Add message component
  src/components/atoms/ImageComponent/Image.jsx
  src/components/atoms/ImageComponent/Image.scss
  src/components/molecules/Message/Message.jsx
  src/components/molecules/Message/Message.scss
  src/components/molecules/index.jsx
  src/images/avatar.png
  src/pages/BaseScreen/BaseScreen.jsx
  src/styles/variables.scss
Labels: scope: ui, type: feat, priority: medium

#65 Feat: Create chat screen
  src/components/molecules/Message/Message.scss
  src/components/organisms/Header/Header.jsx
  src/components/organisms/Header/Header.scss
  src/components/organisms/index.jsx
  src/pages/BaseScreen/BaseScreen.jsx
  src/pages/BaseScreen/BaseScreen.scss
  src/pages/Chat/Chat.jsx
  src/pages/Chat/Chat.scss
  src/styles/global.scss
  src/utils/Mocks.js
Labels: scope: ui, scope: app, type: feat, priority: medium

#37 feat: Setup Firebase
  .env.example
  .eslintrc
  .husky/pre-commit
  firebase.rules
  package.json
  src/App.jsx
  src/Router.jsx
  src/api/ApiService.js
  src/api/Firebase.js
  src/api/index.js
  src/api/types.d.ts
  src/components/atoms/ProtectedRoute/ProtectedRoute.jsx
  src/hooks/index.jsx
  src/hooks/useAuth.jsx
  src/hooks/useChatRoom.jsx
  src/hooks/useDummy.jsx
  src/hooks/usePost.jsx
  src/hooks/usePostComments.jsx
  src/hooks/usePublicChatRooms.jsx
  src/hooks/useResponsive.jsx
  src/hooks/useUserChatRooms.jsx
  src/hooks/useUserDetails.jsx
  src/hooks/useUserPosts.jsx
  src/pages/Home/Home.jsx
  src/pages/Profile/Profile.jsx
  src/styles/global.scss
  src/utils/Reactions.js
  src/utils/index.jsx
  yarn.lock
Labels: scope: api, type: feat, priority: high
